sudo: false
language: python
python:
- 3.2
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install python-opencv
  - sudo dpkg -L python-opencv
  - pip install pipenv

install:
  - pipenv install
  - pipenv install -d

script:
  - ./scripts/test.sh
  - ./scripts/style-check.sh

cache: pip
